### ISSUE TITLE
Cannot read properties of null

### ISSUE THREAD

**Issue by jpfieber** [vkostyanetsky/ObsidianFoodiary#1]
I was very excited to discover your plugin, it plays into what I was hoping to do in my journals soon.  I gave it a quick try but I'm getting an error.  
I have the plugin configured:
![image](https://github.com/vkostyanetsky/ObsidianFoodiary/assets/12567659/ca06f720-f952-4dd7-a127-970ad50ef86f)

I have a note in "_Resources/Ingredients" called "Progresso Creamy Roasted Chicken and Wild Rice.md" that has properties with values as you've described:
![image](https://github.com/vkostyanetsky/ObsidianFoodiary/assets/12567659/a540876d-0fea-4555-ac15-eb93eac46728)

In a journal, I have the following to designate eating 524 grams (1 can) of this soup:
````
```foodiary
Progresso Creamy Roasted Chicken and Wild Rice 524
```
````
The result that is displayed is: 
![image](https://github.com/vkostyanetsky/ObsidianFoodiary/assets/12567659/8d5597db-2f0f-4194-a201-9d61ff6c2f0e)

Am I doing something wrong?

**Comment by vkostyanetsky** [comment]
Hello! I've just tried to reproduce the problem but got no success. Can you have a look at the demo repo below I just made?

 https://github.com/vkostyanetsky/ObsidianFoodiary/tree/main/sampleNullBug

It shows no error so far, but I probably miss some details.

**Comment by vkostyanetsky** [comment]
Welp, forget what I said above, seems like I've just reproduced this one. On my way to fix :)

**Comment by vkostyanetsky** [comment]
Fixed. Can you please upgrade the plugin to 1.2.2 and tell me if is fine now?

**Comment by jpfieber** [comment]
Thanks for getting back to me. No luck.  I now get "Failed to render a food diary:  type of "calories" property in "Zucchini.md" is not number.  Zucchini.md is the last ingredient file in that folder, and it doesn't have any values in the properties yet (I'm working on getting those all populated.  Seems it didn't find a match for the soup file that was there?  Not sure why else it would look at the zucchini file.  If I move the soup ingredient file to a different folder where all the ingredients do have the values populated (I'm working on a script to get a pile of USDA ingredient based files), I get the same "Failed to render a food diary: Cannot read properties of undefined (reading 'forEach')" error as before the update.  Note that I did update the properties to type 'number' (as you can see from the clip above they were 'Text' before) but the change hasn't made a difference.

**Comment by vkostyanetsky** [comment]
> I now get "Failed to render a food diary: type of "calories" property in "Zucchini.md" is not number. Zucchini.md is the last ingredient file in that folder, and it doesn't have any values in the properties yet (I'm working on getting those all populated.

I've just changed the behavior: if a product property doesn't contain a number, it means that the property value is 0. In addition, it sends a message to Obsidian console. It should handle the issue, I guess.

In addition, I slightly changed the line that causes `forEach` issue (should patch the seconds issue you mentioned).

Upgrade to 1.2.3 and tell me how it feel, please.

**Comment by vkostyanetsky** [comment]
There is examples in demo vault on which I tested the patches above:

1. [A product file with no properties filled ](https://github.com/vkostyanetsky/ObsidianFoodiary/blob/main/sample/Products/Zucchini.md?plain=1) (Zucchini.md)
2. [A product file with empty aliases property](https://github.com/vkostyanetsky/ObsidianFoodiary/blob/main/sample/Products/Donuts.md?plain=1)

In case if error still persists, tell me if files in your vault differs from those.

**Comment by jpfieber** [comment]
Working!  I updated the plugin and it's working in my vault now. It nicely gives a big red error when it can't find a product. When it finds all of them it puts them in a table and shows the totals, as it should. Nice work!  Beware, I have a lot of ideas on where this could go, and I'm working on a 'food database' that will make a nice companion for the plugin...

**Comment by vkostyanetsky** [comment]
Sounds great! Let me know if you need something.
